### ISSUE TITLE
Evaluation failure

### ISSUE THREAD

**Issue by hoonkai** [t-taniai/LocalExpStereo#10]
Hi

I was giving this project a go and tried evaluating it against the `Bicycle2` sample. I'm using the matching costs provided in the `Adirondack` link. However, the output I get is the following:

![Screen Shot 2020-05-25 at 3 32 39 am](https://user-images.githubusercontent.com/14197204/82760665-72d2db80-9e38-11ea-8dd0-64e98f288132.png)

I'm already using the corresponding `calib.txt`:

```
cam0=[1948.17 0 532.418; 0 1948.17 488.228; 0 0 1]
cam1=[1948.17 0 614.35; 0 1948.17 488.228; 0 0 1]
doffs=81.931
baseline=173.557
width=1426
height=976
ndisp=125
```

The options I use are:

`"%bin%" -targetDir "%datasetroot%\test2" -outputDir "%resultsroot%\test2" -mode MiddV3 -smooth_weight 0.5`

This is the debug output:

```
Time	Eng	Data	Smooth	all	nonocc
0.000000	-nan(ind)	-nan(ind)	138868.715077	-nan(ind)	99.667810
34.431000	-nan(ind)	-nan(ind)	211043.893761	-nan(ind)	99.978780
68.153000	-nan(ind)	-nan(ind)	268027.314525	-nan(ind)	99.978780
129.158000	-nan(ind)	-nan(ind)	3541.673733	-nan(ind)	99.913212
189.342000	-nan(ind)	-nan(ind)	4004.365720	-nan(ind)	90.420596
250.601000	-nan(ind)	-nan(ind)	4623.280927	-nan(ind)	99.924280
311.898000	-nan(ind)	-nan(ind)	2288.273245	-nan(ind)	100.000000
373.796000	-nan(ind)	-nan(ind)	1892.510750	-nan(ind)	100.000000

```
`Adirondack` works fine though. I haven't tried every sample, but I get similar results from `Classroom2` and `Jadeplant` as well. Does anyone know why this might be the case? Am I missing something?

Thanks

**Comment by t-taniai** [comment]
Hi,

I never heard of such a problem so far from other users. One thing I want to make sure with you is about the following sentences, which I might misunderstand.
> I was giving this project a go and tried evaluating it against the Bicycle2 sample. I'm using the matching costs provided in the Adirondack link.

Did you use matching costs that I provided Adirondack.zip (1.2 GB) when running on Bicycle2, Classroom2, and Jadeplant samples? If so, that is wrong. Matching costs provided in Adirondack can only used for the Adirondack scene. When running on other Middlebury V3 scenes, please download following files (also written in readme)
- [trainingH_im0 (9.2 GB)](https://drive.google.com/file/d/0B-VxeI7PlJE1ZnlQMGdwbm9LSTQ/view?usp=sharing)
- [testH_im0 (12.9 GB)](https://drive.google.com/file/d/0B-VxeI7PlJE1UkdjYjZDNHI0Tkk/view?usp=sharing)

and choose matching cost files in directories of corresponding Middlebury V3 training and test scenes.
