### ISSUE TITLE
what's the mean of ‘ee'? such as: "cv::Mat IL_ee = I_m(rect_ee);"

### ISSUE THREAD

**Issue by KimPhillippCavendish** [t-taniai/LocalExpStereo#11]
Dear Professor,
I am a Undergraduate, i cannot understand as follows (in file ’StereoEnergy.h'):

1.Which words are called 'ee' for short.
So that I cannot understand these objects: disp0_of_le_at_ee, disp0_of_ee_at_le, disp0_of_le_at_le ...

2.why the object 'cost' be computed at 4 times as 'cost00', 'cost01', 'cost10' and ’cost11‘ ?

Thanks for your times!
Wei Xue

**Comment by t-taniai** [comment]
Thank you for your question!

1. It took a few minutes to recall its meaning. But I remember now. Here, E for equal, L for lower, G for greater. Two-letter symbols then indicate neighborhood xy positions relative to a pixel of interest. That is, EE is the position of the pixel itself, and other symbols should indicate 8 neighbors  of the pixel as below.
LL EL GL
EL EE GE
GL GE GG

2. Pairwise functions f(x, y) takes two variables x and y for sites at a pair of neighboring pixels. In graph cuts, x and y are binary, x is assigned either x0 or x1, and y is assigned either y0 and y1 (here, x0, x1, y0, y1 each represents a 3D plane label). Then, if we enumerate all possible values of f(x, y), we should compute  f(x0, y0), f(x0, y1), f(x1, y0), f(x1, y1). The 'cost00', 'cost01', 'cost10' and ’cost11' should represent those pairwise costs.

Best,
Tatsunori
