### ISSUE TITLE
How to get the first correct plane after Label Randomization？

### ISSUE THREAD

**Issue by KimPhillippCavendish** [t-taniai/LocalExpStereo#12]
Dear Professor,

I have also a question: 
How can the algorithm know that the plane which is represented by the label is correct?
Because labels after the first correct one can be estimated by using Energy Function, but the first label has no Reference.

I have read your code, but I can not understand the part of it very well. OTZ

Thanks for your reply!
Wei Xue

**Comment by KimPhillippCavendish** [comment]
Please allow me to make my question clearer:
How to judge a plane good or bad?

Thanks again!
Wei Xue

**Comment by t-taniai** [comment]
Thanks for the question.

If I understand correctly, the question is how we judge the initial random labels are good or bad, correct?

Those initial labels are evaluated by their matching costs and pairwise smoothness costs. At the very first state right after assuming the initial labels, we only know their costs but we do not know they are good or not. Goodness and badness of those costs are evaluated in relation to costs of new proposal labels. If new proposal labels can lead to lower energies, then the initial labels are understood as *relative bad* compared to the new ones. Likewise, if initial labels have lower energies, then they are understood as *relatively good*. 

By repeating these judgements and updates, the labeling eventually becomes a good solution, having low energies, smooth and accurate depths.

Best,
Tatsunori

**Comment by KimPhillippCavendish** [comment]
> Thanks for the question.
> 
> If I understand correctly, the question is how we judge the initial random labels are good or bad, correct?
> 
> Those initial labels are evaluated by their matching costs and pairwise smoothness costs. At the very first state right after assigning the initial labels, we only know their costs but we do not know they are good or not. Goodness and badness of those costs are evaluated in relation to costs of new proposal labels. If new proposal labels can lead to lower energies, then the initial labels are understood as _relative bad_ compared to the new ones. Likewise, if initial labels have lower energies, then they are understood as _relatively good_. We update labels by taking better ones via energy minimization using graph cuts.
> 
> By repeating these judgements and updates, the labeling eventually becomes a good solution, having low energies, smooth and accurate depths.
> 
> Best,
> Tatsunori

Thanks for your time!!! 
But I am also confused. I'm really so sorry for my comprehension ability. QAQ

Yeah, that's what the alpha-expansion dose! LOL!
But according to the related Paper of this code, the Disparity is represented by using Plane ax + by + c.  
Only as we know that the plane is 'fit' the plane of the real object in the real world, the neighboring Pixels in the same plane can be propagated the right plane and through the equation d = ax + by + c to compute the good, right, smooth Disparity.
But the Energy Function can not judge that the plane fits it well or not, cause it only can evaluate the gradient, color similarity, smoothness of disparity between 2 Pixels. 

In the Algorithm, how judge the plane which is represented by the point's label, overlaps the plane of the real object in the real world well or not?

Thank you again,
It's my pleasure to get your answer.

> Thanks for the question.
> 
> If I understand correctly, the question is how we judge the initial random labels are good or bad, correct?
> 
> Those initial labels are evaluated by their matching costs and pairwise smoothness costs. At the very first state right after assigning the initial labels, we only know their costs but we do not know they are good or not. Goodness and badness of those costs are evaluated in relation to costs of new proposal labels. If new proposal labels can lead to lower energies, then the initial labels are understood as _relative bad_ compared to the new ones. Likewise, if initial labels have lower energies, then they are understood as _relatively good_. We update labels by taking better ones via energy minimization using graph cuts.
> 
> By repeating these judgements and updates, the labeling eventually becomes a good solution, having low energies, smooth and accurate depths.
> 
> Best,
> Tatsunori

Thanks for your time!!! 
But I am also confused. I'm really so sorry for my comprehension ability. QAQ

Yeah, that's what the alpha-expansion dose! LOL!
But according to the related Paper of this code, the Disparity is represented by using Plane ax + by + c.  
Only as we know that the plane is 'fit' the plane of the real object in the real world, the neighboring Pixels in the same plane can be propagated the right plane and through the equation d = ax + by + c to compute the good, right, smooth Disparity.
But the Energy Function can not judge that the plane fits it well or not, cause it only can evaluate the gradient, color similarity, smoothness of disparity between 2 Pixels. 

In the Algorithm, how judge the plane which is represented by the point's label, overlaps the plane of the real object in the real world well or not?

Thank you again,
It's my pleasure to get your answer.

**Comment by KimPhillippCavendish** [comment]
> Thanks for the question.
> 
> If I understand correctly, the question is how we judge the initial random labels are good or bad, correct?
> 
> Those initial labels are evaluated by their matching costs and pairwise smoothness costs. At the very first state right after assigning the initial labels, we only know their costs but we do not know they are good or not. Goodness and badness of those costs are evaluated in relation to costs of new proposal labels. If new proposal labels can lead to lower energies, then the initial labels are understood as _relative bad_ compared to the new ones. Likewise, if initial labels have lower energies, then they are understood as _relatively good_. We update labels by taking better ones via energy minimization using graph cuts.
> 
> By repeating these judgements and updates, the labeling eventually becomes a good solution, having low energies, smooth and accurate depths.
> 
> Best,
> Tatsunori

Thanks for your time!!! 
But I am also confused. I'm really so sorry for my comprehension ability. QAQ

Yeah, that's what the alpha-expansion dose! LOL!
But according to the related Paper of this code, the Disparity is represented by using Plane ax + by + c.  
Only as we know that the plane is 'fit' the plane of the real object in the real world, the neighboring Pixels in the same plane can be propagated the right plane and through the equation d = ax + by + c to compute the good, right, smooth Disparity.
But the Energy Function can not judge that the plane fits it well or not, cause it only can evaluate the gradient, color similarity, smoothness of disparity between 2 Pixels. 

In the Algorithm, how judge the plane which is represented by the point's label, overlaps the plane of the real object in the real world well or not?

Thank you again,
It's my pleasure to get your answer.

**Comment by t-taniai** [comment]
Probably, you'd better read this [PatchMatch Stereo](http://www.bmva.org/bmvc/2011/proceedings/paper14/paper14.pdf) paper, from which our matching term has been borrowed.

Here, the matching costs are computed by matching image patches (41x41-size in this and our paper). Basically, a patch is projected as a small square slanted-plane in the 3D space and then projected onto the other image where a patch-based dissimilarity is evaluated. If the object surfaces are sufficiently textured, then such patch-based matching scores can accurately evaluate if a plane fits the local surface (in terms of both its position and gradient) or not. So, the goodness of plane labels can be evaluated by patch-based matching costs.

When surfaces are less textured, then the method basically looks at a more global context and enforces smoothness on the disparity map. It is done as a result of energy minimization.

Best,
Tatsunori
