### ISSUE TITLE
the definition of edges variables

### ISSUE THREAD

**Issue by xxl755** [t-taniai/LocalExpStereo#16]
dear author:
  there is still one question after i've read the paper <WHAT ENERGY FUNCTIONS CAN BE MINIMIZED VIA GRAPH CUTS?>.The paper tell us that how to decompose the edges.the paper has a table to show ABCD variables.the table 3 in paper showing :A=Eij(0,0)=V(fp,fq); B=Eij(0,1)=V(fp,α);C=Eij(1,0)=V(α,fq);D=Eij(1,1)=V(α,α).
but the code give me a different definition about the variable D.
the function computeSmoothnessTermsExpansion in class StereoEnergy have calculated the cost00,cost01 and cost10:

void computeSmoothnessTermsExpansion(const cv::Mat& labeling0_m, Plane label1, cv::Rect region, std::vector<cv::Mat>& cost00, std::vector<cv::Mat>& cost01, std::vector<cv::Mat>& cost10, bool onlyForward = false, int mode = 0) const
	{
		cv::Rect rect_ee = cv::Rect(M + region.x, M + region.y, region.width, region.height);
		cv::Mat label0_ee = labeling0_m(rect_ee);
		cv::Mat coord_ee = coordinates_m(rect_ee);
		cv::Scalar sc = label1.toScalar();
		cv::Mat disp0_of_ee_at_ee = cvutils::channelDot(label0_ee, coord_ee);
		cv::Mat disp1_at_ee = cvutils::channelSum(coord_ee.mul(sc));
		//cv::Mat disp1_at_ee = label1.toDispMap(region); // This changes results due to small numerical differences.

		if (disp0_of_ee_at_ee.depth() != CV_32F){
			disp0_of_ee_at_ee.convertTo(disp0_of_ee_at_ee, CV_32F);
			disp1_at_ee.convertTo(disp1_at_ee, CV_32F);
		}
		cost00 = std::vector<cv::Mat>(neighbors.size());
		cost01 = std::vector<cv::Mat>(neighbors.size());
		cost10 = std::vector<cv::Mat>(neighbors.size());
		for (int i = 0; i < neighbors.size(); i++){
			if (onlyForward && (neighbors[i].y * width + neighbors[i].x <= 0))
				continue;
			cv::Rect rect_le = rect_ee + neighbors[i];
			cv::Mat label0_le = labeling0_m(rect_le);
			cv::Mat coord_le = coordinates_m(rect_le);
			std::cout<<label0_le.at<cv::Vec4f>(0,0)<<std::endl;
			cv::Mat disp0_of_le_at_ee = cvutils::channelDot(label0_le, coord_ee);
			cv::Mat disp0_of_ee_at_le = cvutils::channelDot(label0_ee, coord_le);
			cv::Mat disp0_of_le_at_le = cvutils::channelDot(label0_le, coord_le);
			cv::Mat disp1_at_le = cvutils::channelSum(coord_le.mul(sc));
			if (disp0_of_le_at_ee.depth() != CV_32F){
				disp0_of_le_at_ee.convertTo(disp0_of_le_at_ee, CV_32F);
				disp0_of_ee_at_le.convertTo(disp0_of_ee_at_le, CV_32F);
				disp0_of_le_at_le.convertTo(disp0_of_le_at_le, CV_32F);
				disp1_at_le.convertTo(disp1_at_le, CV_32F);
			}
			cv::Mat smoothnessCoeffL_nb = smoothnessCoeff[mode][i](rect_ee);
		**//cost00:|dp(fp)−dp(fq)| + |dq(fq)−dq(fp)|<=>V(fp,fq)=A**
			cost00[i] = cv::abs(disp0_of_ee_at_ee - disp0_of_le_at_ee) + cv::abs(disp0_of_ee_at_le - disp0_of_le_at_le);
			cv::threshold(cost00[i], cost00[i], params.th_smooth, 0, cv::THRESH_TRUNC);
			cost00[i] = cost00[i].mul(smoothnessCoeffL_nb, params.lambda);
            **//cost01:|dp(fp)−dp(fα)| + |dq(fp)−dq(fα)|<=>V(fp,α)=B**
			cost01[i] = cv::abs(disp0_of_ee_at_ee - disp1_at_ee) + cv::abs(disp0_of_ee_at_le - disp1_at_le);
			cv::threshold(cost01[i], cost01[i], params.th_smooth, 0, cv::THRESH_TRUNC);
			cost01[i] = cost01[i].mul(smoothnessCoeffL_nb, params.lambda);
          **//cost10:|dp(fα)−dp(fq)| + |dq(fq)−dq(fα)|<=>V(fq,α)=C**
			cost10[i] = cv::abs(disp1_at_ee - disp0_of_le_at_ee) + cv::abs(disp1_at_le - disp0_of_le_at_le);
			cv::threshold(cost10[i], cost10[i], params.th_smooth, 0, cv::THRESH_TRUNC);
			cost10[i] = cost10[i].mul(smoothnessCoeffL_nb, params.lambda);
		}

The definition of the cost00 means A in table,cost01 means B,cost10 means C in table.but the code use cost00 as D in table as following in function expandtionMoveBK :
			// ee <-> gg
			// ***
			// ***
			// **@
			for (int y = 0; y < region.height - 1; y++){
				for (int x = 0; x < region.width - 1; x++){
					int i = y*region.width + x;
					int j = (y + 1)*region.width + x + 1;
					float B = cost10[StereoEnergy::NB_GG].at<float>(y, x);
					float C = cost01[StereoEnergy::NB_GG].at<float>(y, x);
					float D = cost00[StereoEnergy::NB_GG].at<float>(y, x);
					graph.add_edge(i, j, std::max(0.f, B + C - D), 0);
					graph.add_tweights(i, C, 0);
					graph.add_tweights(j, D - C, 0);
				}
			}
		}
The variable D should connect with α :D=V(α,α),while the D in code is uncorrelated with α. the cost01 and cost10 are comply with paper.**could you please explain the definition of D in code?**

**Comment by t-taniai** [comment]
D=V(α,α) is omitted because D=V(α,α)=0 from the definition of the smoothness term.

**Comment by xxl755** [comment]
haha,i found it.but i can't sure,because the paper said the A is a constant ,while i found the D is 0. is someone else found the paper's mistake?

**Comment by xxl755** [comment]
should i believe the D in graph is the variable A?

**Comment by xxl755** [comment]
what are going to happen that we ignore the border of rect region 's cost?
bool x0 = x == 0;
				bool x1 = x == region.width - 1;
				bool y0 = y == 0;
				bool y1 = y == region.height - 1;

				if (x0 || x1 || y0 || y1){
					for (int k = 0; k < stereoEnergy->neighbors.size(); k++)
					{     cv::Point ps = cv::Point(x, y) + region.tl();
						cv::Point pt = ps + stereoEnergy->neighbors[k];
						if (region.contains(pt))
							continue;
						if (imageDomain.contains(pt) == false)
							continue;
						// pt is always label0,
						float _cost00 = stereoEnergy->computeSmoothnessTerm(currentLabeling.at<Plane>(ps), currentLabeling.at<Plane>(pt), ps, k, mode);
						float _cost10 = stereoEnergy->computeSmoothnessTerm(label1, currentLabeling.at<Plane>(pt), ps, k, mode);

						graph.add_tweights(s, _cost00, _cost10);\
						auto s_trap=graph.get_trcap(s);
					}
				}
is there will have a big change if we delete the code below?
