### ISSUE TITLE
unresolved external symbol Graph<float,float,double>::reallocate_nodes(int)

### ISSUE THREAD

**Issue by dorp92** [t-taniai/LocalExpStereo#2]
![image](https://user-images.githubusercontent.com/18538356/29762799-018842b8-8bd9-11e7-920e-b6551d9b648b.png)

Fixed by adding:
template class Graph<float,float,double>;
To instances.inc in maxflow project.
I think it should be added to the "How to Run?" section

**Comment by t-taniai** [comment]
Thanks for the feedback. I updated "How to Run?" and mentioned this.

**Comment by luomomo** [comment]
After adding  `template class Graph<float,float,double>；` in  instances.inc 
I still have this problem.
