### ISSUE TITLE
Trial with new data set failed (crashed)

### ISSUE THREAD

**Issue by cregeo** [t-taniai/LocalExpStereo#3]
It crashed at ransac proposer at the function, RANSACPlane(cv::Mat pts, cv::Mat disp, float threshold).

I put the link for the stereo input images used for the testing.

https://photos.google.com/share/AF1QipNMo4mbDj9MjwB2y27NkE6TfgkEiQHo9IZDoOkKm_-DETH7WfPtPY-SGJL_2kKqnA?key=Rkc0Y1MxRVN0Z3Y0el9GQmR6SmV3Ym05STBOWDZ3

**Comment by t-taniai** [comment]
I could not observe any problem for that image pair. I put the image pair in a new directory (without adding info.txt file) and run the program with the following arguments.
-mode MiddV2 -smooth_weight 1 -ndisp 100

**Comment by cregeo** [comment]
Thank you for your quick reply.
If I change the code in MidV2 in main.cpp into the following, with the image pair, 

		IProposer* prop1 = new ExpansionProposer(1);
		IProposer* prop2 = new RandomProposer(7, maxdisp);
		IProposer* prop3 = new ExpansionProposer(2);
		IProposer* prop4 = new RansacProposer(1);
		//stereo.addLayer(5, { prop1, prop4, prop2 });
		//stereo.addLayer(15, { prop3, prop4 });
		//stereo.addLayer(25, { prop3, prop4 });
		stereo.addLayer(8, { prop1, prop4, prop2 });
		stereo.addLayer(24, { prop3, prop4 });
		stereo.addLayer(72, { prop3, prop4 });

I met the error again:
Unhandled exception at 0x00007FF7414049E4 in LocalExpansionStereo.exe: 0xC0000094: Integer division by zero, at RANSACPlane(cv::Mat pts, cv::Mat disp, float threshold) function.

**Comment by t-taniai** [comment]
The target images have 800x489 pixels of resolution. The cell size of 8 pixels produces cells of 1 pixel height at the bottom boundary. I guess this causes a crash in RANSAC proposer.

**Comment by t-taniai** [comment]
I think this issue has been resolved. I modified the LayerManager class so that fractional-size cells at right and bottom boundaries will be merged with their adjacent cells. This guarantees cell width/height is always larger than 1 pixel.
