### ISSUE TITLE
Is there a little bug in Plane.h?

### ISSUE THREAD

**Issue by sunshinnnn** [t-taniai/LocalExpStereo#6]
Plane(float a, float b, float c, **float y**) : a(a), b(b), c(c), v(v){}

Above is the code in Plane.h line 12.
Maybe the **float y** should be **float v**.

**Comment by t-taniai** [comment]
Hi, thanks a lot for letting me know this bug. It seems that it hasn't been a problem, because this constructor is not used in the whole code.
