### ISSUE TITLE
Different results with Middlebury results

### ISSUE THREAD

**Issue by saitakturk** [t-taniai/LocalExpStereo#7]
Hi, 
I tried to reobtain middlebury evaluation results but I got slightly different result than middlebury results. Did you fine tune the parameters or other things that not mentioned.
Edit : I used your costs provided in drive.
<b>My Result</b>
![local_exp](https://user-images.githubusercontent.com/30749092/61369968-a1d00680-a891-11e9-9631-f4f216b32006.png)
<b>Expected Result</b>
![local_exp2](https://user-images.githubusercontent.com/30749092/61369969-a1d00680-a891-11e9-940c-e016ea39bd55.png)

**Comment by t-taniai** [comment]
Hi, it looks like you din't turn on "doDual" option, which enables post processing using left-right consistency check and weighted median filtering. Please confirm that.

**Comment by saitakturk** [comment]
Hi,
Thank you. I turned no "doDual" and the results are matching.
![local_exp5](https://user-images.githubusercontent.com/30749092/61440233-51b17c80-a943-11e9-8267-b0a33548417a.png)
